name: pull_request

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build
      run: make build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: install gotest
      run: go install github.com/rakyll/gotest@latest

    - name: gotest
      run: gotest -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: install reviewdog
      run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest

    - name: go vet
      run: go vet ./... | reviewdog -f=govet -diff="git diff FETCH_HEAD" -reporter=github-pr-review
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}

    - name: staticcheck
      run: staticcheck ./... | reviewdog -f=staticcheck -diff="git diff FETCH_HEAD" -reporter=github-pr-review
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}